using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.JsonWebTokens;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;
using System.Text;

namespace GlossaryBackend.JWT
{
    static class JwtValidators
    {
        public static LifetimeValidator LifetimeValidator = 
            (
                DateTime? notBefore, 
                DateTime? expires, 
                SecurityToken token, 
                TokenValidationParameters parameters
            ) =>
        {
            return 
            notBefore != null && notBefore.Value.ToLocalTime() < DateTime.Now
            && expires != null && expires.Value.ToLocalTime() > DateTime.Now;
        };
    }

    public static class JwtManager
    {
        //Generated by:
        //System.Security.Cryptography.TripleDESCryptoServiceProvider bla = new System.Security.Cryptography.TripleDESCryptoServiceProvider();
        //string temp = Convert.ToBase64String(bla.Key);
        private const string SECRET = "TkluQ3hTak9OQ3BsWlRqTjFhamZ6ckRaWnU1RFFXcGlzZGZnc2RmZ3NkbGZnKCk2YsOfOTgvJkJGSkZKWlQ1dDZyNjdpYlImL09SVms3dGwoVC9ST0xQJSQ4bzZhc2Q1NnM0ZGdmMzQ1aGYtLiw8cGZnPHJldMO8cjBhbmVyZ2RmaGtsLsO2bmU0N3R2N3PDtmVyOHpzZ2huZmQuZ3NlNTh6dG5ic2Vyw7ZwdGw5djgzNHpucDM4NDZ6bmIgIHEyMzRww7bDtnR6OGVybmhzZ2R1ZnNnbGVyOHo1dHEzNMO2bHJlczhnaGrDtnNmOG9sdXp3ZcO2cjhvaWZn";

        private const string REFRESH_SECRET = "jBgtzoXn8JXEixkpdLuL8sU7NHDN/i7AHyysyKtHZI8UpxBxxozq0WMjF646l+KjzFh2KrFvllB7a6xb9yohQLtMKCKk8HBTBl6+YKlkpqmcYHdvnuLKSjBZvA4FPud9L0/Ejg9b0+lKWLenGwGaiWKV7VsihlJZtWQ8tjwtQA4iuH/UACBHfyc4jqDdIf2kmmTBkInWofTSC/8djKoFpCuN7GYJWzcXIHgLxFdoARxCCjPQl8ecQ5xrh9LNBXAom63vXT7/lj29NsNygIMOdHTnGcppEKdtxeE+KFzxlbf2h9PYNjOIhKDbrd+y/OrihN0JpXvGdoH69pwMBsGZYw";

        private static readonly SymmetricSecurityKey AccessSecurityKey = new SymmetricSecurityKey(Convert.FromBase64String(SECRET));
        private static readonly SymmetricSecurityKey RefreshSecurityKey = new SymmetricSecurityKey(Convert.FromBase64String(REFRESH_SECRET));

        public static string GenerateAccessToken(ClaimsPrincipal principal, TimeSpan expiresIn)
        {
            JwtSecurityTokenHandler tokenHandler = new JwtSecurityTokenHandler();

            SigningCredentials credentials = new SigningCredentials(AccessSecurityKey, SecurityAlgorithms.HmacSha256Signature);

            SecurityTokenDescriptor tokenDescriptor = new SecurityTokenDescriptor()
            {
                IssuedAt = DateTime.Now,
                Expires = DateTime.Now.Add(expiresIn),
                NotBefore = DateTime.Now,
                Subject = new ClaimsIdentity(principal.Claims),
                SigningCredentials = credentials
            };

            JwtSecurityToken token = tokenHandler.CreateJwtSecurityToken(tokenDescriptor);

            return tokenHandler.WriteToken(token);
        }

        public static string GenerateRefreshToken(ClaimsPrincipal principal, TimeSpan expiresIn)
        {
            JwtSecurityTokenHandler tokenHandler = new JwtSecurityTokenHandler();

            SigningCredentials credentials = new SigningCredentials(RefreshSecurityKey, SecurityAlgorithms.HmacSha256Signature);

            SecurityTokenDescriptor tokenDescriptor = new SecurityTokenDescriptor()
            {
                IssuedAt = DateTime.Now,
                Expires = DateTime.Now.Add(expiresIn),
                NotBefore = DateTime.Now,
                Subject = new ClaimsIdentity(principal.Claims),
                SigningCredentials = credentials
            };

            JwtSecurityToken token = tokenHandler.CreateJwtSecurityToken(tokenDescriptor);

            return tokenHandler.WriteToken(token);
        }

        public static ClaimsPrincipal AuthenticateToken(string token)
        {
            JwtSecurityTokenHandler tokenHandler = new JwtSecurityTokenHandler();

            if (!tokenHandler.CanReadToken(token))
                return null;
            
            tokenHandler.ValidateToken(token, new TokenValidationParameters()
            {
                RequireExpirationTime = true,
                RequireSignedTokens = true,
                ValidateLifetime = true,
                ValidateAudience = false,
                ValidateIssuer = false,
                IssuerSigningKey = AccessSecurityKey,
                LifetimeValidator = JwtValidators.LifetimeValidator,

            },out SecurityToken scToken);

            JwtSecurityToken jwt = scToken as JwtSecurityToken;

            if(jwt != null && jwt.Claims != null)
            {
                return new ClaimsPrincipal(new ClaimsIdentity(jwt.Claims));
            }
            else
            {
                return null;
            }
        }
    }
}